- name: Refresh CloudForms VMs
  connection: local
  hosts: all
  gather_facts: no
  tasks:
  - name: Get Info and Refresh a CloudForms VM
    block
    - name: Get Info CloudForms VM
      uri:
        url: "https://cfui01.presidencia.gob.mx/api/vms/99000000000674?expand=software&attributes=ipaddresses"
        method: GET
        user: admin
        password: redhat2019!
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
        body: >
          {
             "action" : "refresh"
          }
        body_format: json
      register: vm
      delegate_to: localhost
      
    - name: Set Fact ipaddress
      set_fact:
        ipaddress: "{{ vm.json.ipaddresses[0] }}"
        
    - name: Refresh CloudForms VM
      uri:
        url: "{{ cloudforms.href }}"
        method: POST
        user: "{{ cf_user }}"
        password: "{{ cf_pw }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
        body: >
          {
             "action" : "refresh"
          }
      delegate_to: localhost
    until: ipaddress is defined

- name: Install Ticketmonster App
  hosts: all
  
  roles:
   - common
   - jboss-standalone
   - java-app
